# Default configuration for spinq_qv simulations
# All device parameters from Si/SiGe experimental data

device:
  # Gate fidelities (average gate fidelity)
  F1: 0.99926          # Single-qubit gate fidelity (99.926%)
  F2: 0.998            # Two-qubit gate fidelity (99.8%)
  
  # Coherence times (seconds)
  T1: 1.0              # Amplitude damping time (1 second)
  T2: 99.0e-6          # Hahn echo T2 (99 µs)
  T2_star: 20.0e-6     # Ramsey dephasing T2* (20 µs)
  
  # Gate durations (seconds)
  t_single_gate: 60.0e-9   # Single-qubit Xπ/2 gate (60 ns)
  t_two_gate: 40.0e-9      # Two-qubit CZ gate (40 ns)
  
  # Coherent error parameters (explicit defaults)
  single_qubit_overrotation_rad: 0.0   # Over-rotation angle (rad)
  coherent_axis: 'z'                   # Default coherent-axis for systematic errors
  residual_zz_phase: 0.0               # Residual ZZ phase (radians)

  # Crosstalk parameters (NEW)
  zz_crosstalk_strength: 0.0           # Always-on ZZ crosstalk (rad/s)
  control_crosstalk_fraction: 0.0      # Fractional leakage to spectator qubits

  # SPAM parameters (NEW - replaces legacy F_readout/F_init)
  state_prep_error: 0.006              # Probability of |1> after reset (1 - F_init)
  meas_error_1given0: 0.00015          # P(measure 1 | true state is |0>) - false positive
  meas_error_0given1: 0.00015          # P(measure 0 | true state is |1>) - false negative
  t_readout: 10.0e-6                   # Readout time (10 µs)

  # Time-dependent / drift defaults (NEW)
  coherent_drift_std: 0.0              # Stddev of coherent error drift (radians)
  sigma_drift_fraction: 0.0            # Relative drift in T2* noise magnitude (0-1)

simulation:
  backend: "statevector"    # Options: statevector, density_matrix, mcwf, tensornet
  n_circuits: 50            # Number of random circuits per width (IBM uses 100+)
  n_shots: 1000             # Shots per circuit (1000-5000 recommended)
  widths: [2, 3, 4, 5, 6]   # QV circuit widths to test
  random_seed: 42           # For reproducibility (null = random)

metadata:
  experiment_name: "baseline_qv"
  description: "Baseline Quantum Volume simulation with Si/SiGe donor spin parameters"
  notes: "Using experimental values: F1=99.926%, F2=99.8%, T1=1s, T2=99µs"
