device:
  F1: 0.9956115438525223
  F2: 0.9582750283499287
  T1: 0.310923848233593
  T2: 0.0013608134615715353
  T2_star: 5.567842006766662e-06
  t_single_gate: 6.862473328276409e-08
  t_two_gate: 4.0e-08
  single_qubit_overrotation_rad: 0.0
  coherent_axis: z
  residual_zz_phase: 10000.0
  zz_crosstalk_strength: 25118.019868874482
  control_crosstalk_fraction: 0.01728385017258716
  state_prep_error: 0.023611929616002246
  meas_error_1given0: 0.0003
  meas_error_0given1: 0.009529587887586401
  t_readout: 1.0e-05
  coherent_drift_std: 0.0
  sigma_drift_fraction: 6.0e-05
simulation:
  backend: statevector
  n_circuits: 100
  n_shots: 5000
  widths:
  - 2
  - 3
  - 4
  - 5
  - 6
  - 7
  - 8
  - 9
  - 10
  - 11
  - 12
  random_seed: 42
metadata:
  experiment_name: production_qv_campaign
  description: Full production Quantum Volume campaign for Si/SiGe baseline characterization
  notes: 'Production configuration with:

    - 100 circuits per width (IBM standard)

    - 5000 shots per circuit (high precision)

    - Widths 2-12 (QV from 4 to 4096)

    - Estimated runtime: ~6-12 hours on 8-core CPU with parallelization

    '
