# Baseline configuration for Quantum Volume simulations
# Device parameters from Si/SiGe experimental data

device:
  # Gate fidelities (average gate fidelity)
  F1: 0.99926          # Single-qubit gate fidelity (99.926%)
  F2: 0.998            # Two-qubit gate fidelity (99.8%)
  
  # Coherence times (seconds)
  T1: 1.0              # Amplitude damping time (1 second)
  T2: 99.0e-6          # Hahn echo T2 (99 µs)
  T2_star: 20.0e-6     # Ramsey dephasing T2* (20 µs)
  
  # Gate durations (seconds)
  t_single_gate: 60.0e-9   # Single-qubit Xπ/2 gate (60 ns)
  t_two_gate: 40.0e-9      # Two-qubit CZ gate (40 ns)
  
  # Coherent & crosstalk defaults (explicit)
  single_qubit_overrotation_rad: 0.0
  coherent_axis: 'z'
  residual_zz_phase: 0.0
  zz_crosstalk_strength: 0.0
  control_crosstalk_fraction: 0.0

  # SPAM parameters (replaces legacy F_readout / F_init)
  state_prep_error: 0.006              # 1 - 0.994
  meas_error_1given0: 0.00015          # (1 - 0.9997)/2
  meas_error_0given1: 0.00015          # (1 - 0.9997)/2
  t_readout: 10.0e-6                   # Readout time (10 µs)

  # Time-dependent / drift defaults
  coherent_drift_std: 0.0
  sigma_drift_fraction: 0.0

simulation:
  backend: "statevector"    # Options: statevector, density_matrix, mcwf, tensornet
  n_circuits: 50            # Number of random circuits per width (IBM uses 100+)
  n_shots: 1000             # Shots per circuit (1000-5000 recommended)
  widths: [2, 3, 4, 5, 6]   # QV circuit widths to test
  random_seed: 42           # For reproducibility (null = random)

metadata:
  experiment_name: "baseline_qv"
  description: "Baseline Quantum Volume simulation with Si/SiGe donor spin parameters"
  notes: "Using experimental values: F1=99.926%, F2=99.8%, T1=1s, T2=99µs"
