# Test configuration for integration tests (small, fast runs)

device:
  F1: 0.99926
  F2: 0.998
  T1: 1.0
  T2: 99.0e-6
  T2_star: 20.0e-6
  t_single_gate: 60.0e-9
  t_two_gate: 40.0e-9
  # SPAM parameters (NEW)
  state_prep_error: 0.006
  meas_error_1given0: 0.00015
  meas_error_0given1: 0.00015
  t_readout: 10.0e-6

  # Coherent & crosstalk defaults
  single_qubit_overrotation_rad: 0.0
  coherent_axis: 'z'
  residual_zz_phase: 0.0
  zz_crosstalk_strength: 0.0
  control_crosstalk_fraction: 0.0

  # Time-dependent / drift defaults
  coherent_drift_std: 0.0
  sigma_drift_fraction: 0.0

simulation:
  backend: "statevector"
  n_circuits: 10          # Small for testing
  n_shots: 500            # Small for testing
  widths: [2, 3, 4]       # Limited range for testing
  random_seed: 12345

metadata:
  experiment_name: "test_pipeline"
  description: "Integration test configuration with reduced circuit/shot counts"
  notes: "Used for pytest integration tests"
